global:
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 10.22.8.5:9093    
rule_files:
  #- "/monit/rules/*.yml"
  - "/etc/prometheus/*.rules"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']


  - job_name: 'gitlab'
    scrape_interval: 5s
    static_configs:
    - targets: ['10.22.30.3:9100']
      labels:
        instance: 'gitlab'

  - job_name: 'Linux-Os'
    file_sd_configs:
    - files: ['/etc/prometheus/*.yml']
      refresh_interval: 10s
