global:
  resolve_timeout: 2m
route:
  receiver: webhook
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 15m
  group_by: [alertname]
receivers:
- name: webhook
  webhook_configs:
  - url: http://10.98.2.200:8060/dingtalk/webhook1/send 
    send_resolved: true
    
